version: '3.7'

services:

    mongodb:
        image: mongo:latest
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: webapp
            MONGODB_DATA_DIR: /data/db
        ports:
            - "27017:27017"
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend
    
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - backend
    
    api:
        build: 
            context: ./
            dockerfile: Dockerfile
        # command: python3 -m debugpy --listen 0.0.0.0:4444 api/main.py --host=0.0.0.0 --port=5000
        command: python api/main.py --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
            - "5678:5678"
        environment:
            FLASK_APP: "app"
            FLASK_DEBUG: 1
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "admin"
            MONGODB_PASSWORD: "password"
            REDIS_HOST: "redis"
            REDIS_PORT: 6379
            REDIS_DB: 0
            REDIS_URL: "redis://redis:6379/0"
        volumes:
            - ./:/src
        depends_on: 
            - mongodb
        networks:
            - backend

networks:
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local